
# Auto-imported playlist from: /Users/pillu/Music/Downloads
fav = [
    '/Users/pillu/Music/Downloads/Undertale - NGAHHH  Spear of Justice Song Mix.mp3',
    '/Users/pillu/Music/Downloads/048 Alphys UNDERTALE Soundtrack - Toby Fox.mp3',
    '/Users/pillu/Music/Downloads/Shinobu Theme from Demon Slayer.mp3',
    '/Users/pillu/Music/Downloads/051 Another Medium UNDERTALE Soundtrack - Toby Fox.mp3',
    '/Users/pillu/Music/Downloads/071. Undertale (UNDERTALE Soundtrack) - Toby Fox.mp3',
    '/Users/pillu/Music/Downloads/035 Bird That Carries You Over A Disproportionately Small Gap UNDERTALE Soundtra.mp3',
    '/Users/pillu/Music/Downloads/matrix bl studio loop slowed.mp3',
    '/Users/pillu/Music/Downloads/087 Hopes And Dreams UNDERTALE Soundtrack - Toby Fox.mp3',
    '/Users/pillu/Music/Downloads/Катя Лель - Мой мармеладный.mp3',
    '/Users/pillu/Music/Downloads/JAWNY - Honeypie Official Video.mp3',
    '/Users/pillu/Music/Downloads/060 Wrong Enemy  UNDERTALE Soundtrack - Toby Fox.mp3',
    '/Users/pillu/Music/Downloads/015. sans. (UNDERTALE Soundtrack) - Toby Fox.mp3',
    '/Users/pillu/Music/Downloads/A Double Suicide.mp3',
    '/Users/pillu/Music/Downloads/096 Last Goodbye UNDERTALE Soundtrack - Toby Fox.mp3',
    '/Users/pillu/Music/Downloads/Meant To Be.mp3',
    '/Users/pillu/Music/Downloads/062 Oh Dungeon UNDERTALE Soundtrack - Toby Fox.mp3',
    '/Users/pillu/Music/Downloads/050. Metal Crusher (UNDERTALE Soundtrack) - Toby Fox.mp3',
    '/Users/pillu/Music/Downloads/sombr - back to friends official video.mp3',
    '/Users/pillu/Music/Downloads/risk.mp3',
    '/Users/pillu/Music/Downloads/matrix bl studio loop - chrmbchrmb.mp3',
    '/Users/pillu/Music/Downloads/049 Its Showtime UNDERTALE Soundtrack - Toby Fox.mp3',
    '/Users/pillu/Music/Downloads/010 Ghost Fight UNDERTALE Soundtrack - Toby Fox.mp3',
    '/Users/pillu/Music/Downloads/SALSA.mp3',
    '/Users/pillu/Music/Downloads/008 Unnecessary Tension UNDERTALE Soundtrack - Toby Fox.mp3',
    '/Users/pillu/Music/Downloads/Kanroji VS Zohakuten.mp3',
    '/Users/pillu/Music/Downloads/Tame Impala - The Less I Know The Better Official Video.mp3',
    '/Users/pillu/Music/Downloads/091 Final Power UNDERTALE Soundtrack - Toby Fox.mp3',
    '/Users/pillu/Music/Downloads/057 Live Report UNDERTALE Soundtrack - Toby Fox.mp3',
    '/Users/pillu/Music/Downloads/081 An Ending UNDERTALE Soundtrack - Toby Fox.mp3',
    '/Users/pillu/Music/Downloads/Run Rabbit Run.mp3',
    '/Users/pillu/Music/Downloads/036 Dummy UNDERTALE Soundtrack - Toby Fox.mp3',
    '/Users/pillu/Music/Downloads/Miki Matsubara - Stay With Me HD (Club Mix).mp3',
    '/Users/pillu/Music/Downloads/044 Tem Shop UNDERTALE Soundtrack - Toby Fox.mp3',
    '/Users/pillu/Music/Downloads/030 Undyne UNDERTALE Soundtrack - Toby Fox.mp3',
    '/Users/pillu/Music/Downloads/pupsies - misery. (Music Video).mp3',
    '/Users/pillu/Music/Downloads/059. Spider Dance (UNDERTALE Soundtrack) - Toby Fox.mp3',
    '/Users/pillu/Music/Downloads/Heartache.mp3',
    '/Users/pillu/Music/Downloads/077. ASGORE (UNDERTALE Soundtrack) - Toby Fox.mp3',
    '/Users/pillu/Music/Downloads/The Less I Know The Better.mp3',
    '/Users/pillu/Music/Downloads/Lana Del Rey - Salvatore (Lyrics).mp3',
    '/Users/pillu/Music/Downloads/079 Your Best Nightmare UNDERTALE Soundtrack - Toby Fox.mp3',
    '/Users/pillu/Music/Downloads/011 Determination UNDERTALE Soundtrack - Toby Fox.mp3',
    '/Users/pillu/Music/Downloads/Nyeh Heh Heh.mp3',
    '/Users/pillu/Music/Downloads/Im going to be a squashed cheese ball today.mp3',
    '/Users/pillu/Music/Downloads/068 Death By Glamour UNDERTALE Soundtrack - Toby Fox.mp3',
    "/Users/pillu/Music/Downloads/Joy Crookes - Feet Don't Fail Me Now (Official Video).mp3",
    '/Users/pillu/Music/Downloads/Kizuna No Kiseki.mp3',
    '/Users/pillu/Music/Downloads/Undertale - Papyrus Theme Song - Bonetrousle.mp3',
    '/Users/pillu/Music/Downloads/099 Power Of NEO UNDERTALE Soundtrack - Toby Fox.mp3',
    '/Users/pillu/Music/Downloads/072 Song That Might Play When You Fight Sans UNDERTALE Soundtrack - Toby Fox.mp3',
    '/Users/pillu/Music/Downloads/043 Temmie Village UNDERTALE Soundtrack - Toby Fox.mp3',
    '/Users/pillu/Music/Downloads/track.mp3',
    '/Users/pillu/Music/Downloads/Music Sounds Better With You Radio Edit.mp3',
    '/Users/pillu/Music/Downloads/Once Upon a Time.mp3',
    '/Users/pillu/Music/Downloads/Sade - Smooth Operator - Official - 1984.mp3',
    '/Users/pillu/Music/Downloads/088 Burn In Despair UNDERTALE Soundtrack - Toby Fox.mp3',
    '/Users/pillu/Music/Downloads/Joy Crookes - Feet Dont Fail Me Now Official Video.mp3',
    '/Users/pillu/Music/Downloads/065. CORE (UNDERTALE Soundtrack) - Toby Fox.mp3',
    '/Users/pillu/Music/Downloads/MUGEN.mp3',
    '/Users/pillu/Music/Downloads/Admiring You - Private Pure Love Train Hakari Idle Death Gamble Theme Jujutsu Ka.mp3',
    '/Users/pillu/Music/Downloads/061 Oh One True Love UNDERTALE Soundtrack - Toby Fox.mp3',
    '/Users/pillu/Music/Downloads/Malcolm Todd - Earrings Official Visualizer.mp3',
    '/Users/pillu/Music/Downloads/085. Fallen Down (Reprise) (UNDERTALE Soundtrack) - Toby Fox.mp3',
    '/Users/pillu/Music/Downloads/089 SAVE The World UNDERTALE Soundtrack - Toby Fox.mp3',
    '/Users/pillu/Music/Downloads/Joy.mp3',
    '/Users/pillu/Music/Downloads/-.mp3',
    '/Users/pillu/Music/Downloads/She  Him - I Thought I Saw Your Face Today Official Lyric Video.mp3',
    '/Users/pillu/Music/Downloads/009 Enemy Approaching UNDERTALE Soundtrack - Toby Fox.mp3',
]
